### Registrar uma nova leitura de RFID
POST https://api-rfid-springboot.onrender.com/api/leitura
Content-Type: application/json

{
  "rfid_tag": "JAVASPRING_OK_2",
  "leitor_id": "TESTE_INTELLIJ_02"
}